# Profile layer 0.
apiVersion: batch/v1
kind: Job
metadata:
  generateName: wheeler-profile-layer-0-
  labels:
    eidf/user: cwheeler-eidf220
    kueue.x-k8s.io/queue-name: eidf220ns-user-queue
    kueue.x-k8s.io/priority-class: batch-workload-priority
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 6000
  template:
    metadata:
      labels:
        eidf/user: cwheeler-eidf220
    spec:
      nodeSelector:
        nvidia.com/gpu.product: "NVIDIA-A100-SXM4-40GB"
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: cwheeler-data
      securityContext:
         fsGroup: 5455
      containers:
      - name: profile-kernel
        image: camwheeler135/profile_layer_0:v0.0.X # Replace with appropriate version number.
        imagePullPolicy: Always
        command: ["/bin/bash", "-c"]
        args:
        - |
          uv run --no-sync time_cuda_vs_torch.py --kernel matmul
          EXIT_CODE=$?
          echo "Fixing permissions..."
          chown -R 28853:5455 /data
          chmod -R 775 /data
          exit $EXIT_CODE
        resources:
          requests:
           nvidia.com/gpu: 1
           cpu: 8
           memory: 32Gi
          limits:
            nvidia.com/gpu: 1
            cpu: 8
            memory: 32Gi
        volumeMounts:
        - name: data
          mountPath: /data
      restartPolicy: Never