FROM nvidia/cuda:12.6.3-devel-ubuntu22.04

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 python3-venv python3-dev git ca-certificates \
    && rm -rf /var/lib/apt/lists/*

COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv

WORKDIR /app
COPY pyproject.toml uv.lock ./

# Install torch from the CUDA wheel index (important)
ENV UV_TORCH_BACKEND=cu126
RUN uv sync --frozen --no-dev --python 3.12

COPY config.py train.py download_and_tokenise.py dataset.py main.py /app
COPY models /app/models


ENV PATH="/app/.venv/bin:$PATH"