FROM nvidia/cuda:12.6.3-devel-ubuntu22.04

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 python3-venv python3-dev git ca-certificates \
    && rm -rf /var/lib/apt/lists/*

COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv

WORKDIR /app
COPY pyproject.toml uv.lock ./

# Install torch from the CUDA wheel index
ENV UV_TORCH_BACKEND=cu126

# This time we actually want the dev params.
RUN uv sync --frozen --python 3.12

# CUDA source code
COPY cudasrc /app/cudasrc 

# Handle the setup so we compile on image build
# This will insert the .so file into the image.
COPY setup.py /app/setup.py
RUN uv run python /app/setup.py build_ext --inplace

# Python wrappers around C++
COPY wrappers /app/wrappers

# Actual tests
COPY tests /app/tests

ENV PATH="/app/.venv/bin:$PATH"

# Entrypoint will be set on K8s.